name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  offline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run offline tests
        run: scripts/test.sh
